---
- name: Get nodes
  shell: kubectl get nodes -o wide
  register: nodes
- debug: msg={{ nodes }}

- name: Label master nodetype master
  shell: kubectl label node  "{{ item }}" nodetype=master --overwrite
  register: response
  with_items:
    - '{{ groups["master"] }}'
- debug: msg={{ response }}
    
- name: Label worker nodetype worker
  shell: kubectl label node  "{{ item }}" nodetype=worker --overwrite
  register: response
  with_items:
    - '{{ groups["node"] }}'
- debug: msg={{ response }}

- name: Get nodes
  shell: kubectl get nodes -o wide
  register: nodes
- debug: msg={{ nodes }