---
- name: Cluster
  shell: kubectl cluster-info
  register: response
- debug: msg={{ response.stdout_lines }}
  
- name: Nodes
  shell: kubectl get nodes --all-namespaces -o wide
  register: response
- debug: msg={{ response.stdout_lines }}
      
- name: Pods
  shell: kubectl get pods --all-namespaces -o wide
  register: response
- debug: msg={{ response.stdout_lines }}
  
- name: Services
  shell: kubectl get services --all-namespaces -o wide
  register: response
- debug: msg={{ response.stdout_lines }}
  
- name: Describe nodes
  shell: kubectl describe nodes
  register: response
- debug: msg={{ response.stdout_lines }}