---
- name: Remove old NTP servers on {{ inventory_hostname }}
  lineinfile:
    dest: /etc/ntp.conf
    regexp: "^server"
    state: absent

- name: Configure NTP servers on {{ inventory_hostname }}
  lineinfile:
    dest: /etc/ntp.conf
    line: "server {{ item }} iburst"
  with_items: "{{ bootstrap_server_ip }}"

- name: Stop the ntpd service if running on {{ inventory_hostname }} centos
  service:
    name: ntpd
    state: stopped
  when: linux_os == "centos"

- name: Stop the ntpd service if running on {{ inventory_hostname }} ubuntu
  service:
    name: ntp
    state: stopped
  when: linux_os == "ubuntu"

- name: Manually sync time with ntp server on {{ inventory_hostname }}
  command: ntpdate -u "{{bootstrap_server_ip}}"

- name: Start ntpd on {{ inventory_hostname }}  centos
  service:
    name: ntpd
    state: started
  when: linux_os == "centos"

- name: Start ntpd on {{ inventory_hostname }}  ubuntu
  service:
    name: ntpd
    state: started
  when: linux_os == "ubuntu"

- name: check ntp sync state
  shell: ntpstat | awk 'NR==1{print $1}'
  register: sync_status
  until: sync_status.stdout == "synchronised"
  retries: 29
  delay: 10