---
- name: download consul
  unarchive: 
    src: "{{ consul_url }}"
    dest: /tmp
    copy: no
  tags: download

- name: helm install consul
  shell: helm install --name hashicorp /tmp/consul-helm-{{ consul_version }}/
  register: response
  become_user: "{{ cloud_user }}"
- debug: msg={{ response }}

