---
- name: Setup Cluster underlay 
  hosts: kube_cluster
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  roles:
    #- { role: os, tags: os }
    #- { role: swap, tags: swapp }
    #- { role: packages, tags: packages }
    #- { role: ping, tags: ping }
    #- { role: ntp, tags: ntp }
    #- { role: docker, tags: docker }
    #- { role: kubernetes/underlay, tags: underlay }
    #- { role: ssh, tags: ssh }
    # - { role: glusterfs/general, tags: glusterfs-general }

- name: Setup glusterfs server 
  hosts: glusterfs
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  roles:
    #- { role: glusterfs/server, tags: glusterfs-server }

- hosts: master
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni/calico, tags: cni/calico }
    - { role: cni/multus, tags: cni/multus }
    
- hosts: node
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: kubernetes/node, tags: node }
    - { role: cni/multus/install, tags: cni/multus/install }

- hosts: kube_cluster
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: calicoctl, tags: calicoctl }

- hosts: master
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/nodes, tags: kubernetes/nodes }
    - { role: cni/multus/master, tags: cni/multus/install }
    
- hosts: node
  gather_facts: no
  become: yes
  roles:
    - { role: cni/multus/node, tags: cni/multus/node }
    - { role: ipsec, tags: ipsec }

- hosts: master
  gather_facts: no
  roles:
    - { role: helm, tags: helm }
    - { role: consul, tags: consul }
    - { role: rook-ceph, tags: rook-ceph }
    - { role: metric-server, tags: metric-server }
    - { role: prometheus, tags: prometheus}
    - { role: grafana, tags: grafana}
    - { role: sysdig-falco, tags: sysdig-falco}
    - { role: log-aggregation, tags: log-aggregation}
    - { role: istio, tags: istio}
    - { role: kubernetes/status, tags: kubernetes/status }
    - { role: cmm-spinner, tags: cmm-spinner }

- hosts: node
  gather_facts: no
  become: yes
  roles:
    #- { role: sriov, tags: sriov }