---
- name: install nfs
  hosts: node
  gather_facts: yes
  roles:
    - { role: nfs/node, tags: nfs/node }

- name: install nfs on kubernetes
  hosts: master
  roles:
    - { role: nfs/kubernetes, tags: nfs/kubernetes }