---
- name: Setup Cluster underlay 
  hosts: kube_cluster
  gather_facts: yes
  become: yes
  tasks:
    - name: Reset Kubernetes component
      shell: "kubeadm reset --force"
      ignore_errors: True
    
    - name: restart kubelet
      systemd:
        state: restarted
        name: kubelet