---
- name: Setup Cluster underlay 
  hosts: kube_cluster
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: os, tags: os }
    - { role: swap, tags: swapp }
    - { role: packages, tags: packages }
    - { role: ntp, tags: ntp }
    - { role: docker, tags: docker }
    - { role: kubernetes/underlay, tags: underlay }
    - { role: ssh, tags: ssh }
    - { role: glusterfs/general, tags: glusterfs-general }

- name: Setup glusterfs server 
  hosts: glusterfs
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: glusterfs/server, tags: glusterfs-server }

# - hosts: master
#   gather_facts: no
#   become: yes
#   roles:
#     - { role: kubernetes/master, tags: master }
#     - { role: cni, tags: cni }
    
# - hosts: node
#   gather_facts: no
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
# #    - { role: cni, tags: cni }
#     - { role: kubernetes/node, tags: node }

# - hosts: kube_cluster
#   gather_facts: yno
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - { role: calicoctl, tags: calicoctl }

# - hosts: master
#   gather_facts: no
#   roles:
#     - { role: helm, tags: helm }
#     - { role: istio, tags: istio }