---
- name: install  packages
  yum: 
    name: "{{ item.pkgname }}"
    state: "present"
  with_items:
    - { pkgname: "epel-release"  }
    - { pkgname: "ntp" }
    - { pkgname: "bridge-utils" }
    - { pkgname: "python3"}
    - { pkgname: "python34-setuptools"}
    - { pkgname: "golang" }
    - { pkgname: "git"}
    - { pkgname: "ansible"}
    - { pkgname: "sshpass"}
    - { pkgname: "whois"}
    - { pkgname: "java-11-openjdk"}
    
- name: install pip
  easy_install:
    name: pip
    state: latest

- name: install pip packages
  pip:
    name: "{{ item.pkgname }}"
    state: latest
  loop:
    - { pkgname: "docker"  }
    - { pkgname: "pexpect"  }