---
- name: install  packages
  apt:
    name: "{{ item.pkgname }}"
    state: present
  with_items:
    - { pkgname: "ntp" }
    - { pkgname: "ntpstat" }
    - { pkgname: "ntpdate" }
    - { pkgname: "ntpsec-ntpdate" }
    - { pkgname: "bridge-utils" }
    - { pkgname: "python"}
    - { pkgname: "python-setuptools"}
    - { pkgname: "python-pip"}
    - { pkgname: "python-dev"}
    - { pkgname: "python3"}
    - { pkgname: "python3-setuptools"}
    - { pkgname: "python3-pip"}
    - { pkgname: "python3-dev"}
    - { pkgname: "build-essential"}
    - { pkgname: "golang" }
    - { pkgname: "git"}
    - { pkgname: "ansible"}
    - { pkgname: "sshpass"}
    - { pkgname: "whois"}
    - { pkgname: "openjdk-11-jdk"}
    - { pkgname: "openjdk-11-jre"}
    - { pkgname: "bind9"}
    - { pkgname: "dnsutils"}
    - { pkgname: "linux-tools-common"}

- name: Upgrade all packages on ubuntu
  apt:
    name: "*"
    state: latest
  when: linux_os == "ubuntu"

- name: Update all packages on ubuntu
  apt:
    upgrade: dist
  when: linux_os == "ubuntu"

# - name: Disable ondemand
#   become: true
#   service:
#     enabled: no
#     name: ondemand
#     state: stopped

# - name: Install cpupower
#   become: true
#   shell: sudo apt-get --yes install linux-tools-common linux-tools-$(uname -r)
#   args:
#     warn: False
#   register: response

# - name: debug output
#   debug: 
#     msg: "{{ response }}"

# - name: Create /lib/systemd/system/cpupower.service
#   become: true
#   template:
#     src: "{{ item }}"
#     dest: /lib/systemd/system/cpupower.service
#     mode: "0644"
#   with_items:
#     - cpupower.j2

# - name: Show /lib/systemd/system/cpupower.service
#   become: true
#   shell: cat /lib/systemd/system/cpupower.service
#   register: response

# - name: debug output
#   debug: 
#     msg: "{{ response }}"

# - name: Start cpupower
#   become: true
#   service:
#     name: cpupower
#     state: restarted
#     enabled: yes
#   register: service

# - name: debug output
#   debug: 
#     msg: "{{ service }}"