---
- name: install  packages
  apt:
    name: "{{ item.pkgname }}"
    state: present
  with_items:
    - { pkgname: "ntp" }
    - { pkgname: "bridge-utils" }
    - { pkgname: "python3"}
    - { pkgname: "golang" }
    - { pkgname: "git"}
    - { pkgname: "ansible"}
    - { pkgname: "sshpass"}
    - { pkgname: "whois"}
    - { pkgname: "openjdk-11-jdk"}
    - { pkgname: "openjdk-11-jre"}
    - { pkgname: "bind9"}
    - { pkgname: "dnsutils"}
    - { pkgname: "linux-tools-common"}