---
- name: install  packages
  apt:
    name: "{{ item.pkgname }}"
    state: present
  with_items:
    - { pkgname: "ntp" }
    - { pkgname: "bridge-utils" }
    - { pkgname: "python"}
    - { pkgname: "python-setuptools"}
    - { pkgname: "python-pip"}
    - { pkgname: "python-dev"}
    - { pkgname: "python3"}
    - { pkgname: "python3-setuptools"}
    - { pkgname: "python3-pip"}
    - { pkgname: "python3-dev"}
    - { pkgname: "build-essential"}
    - { pkgname: "golang" }
    - { pkgname: "git"}
    - { pkgname: "ansible"}
    - { pkgname: "sshpass"}
    - { pkgname: "whois"}
    - { pkgname: "openjdk-11-jdk"}
    - { pkgname: "openjdk-11-jre"}
    - { pkgname: "bind9"}
    - { pkgname: "dnsutils"}
    - { pkgname: "linux-tools-common"}

- name: Upgrade all packages on ubuntu
  apt:
    name: "*"
    state: latest
  when: linux_os == "ubuntu"

- name: Update all packages on ubuntu
  apt:
    upgrade: dist
  when: linux_os == "ubuntu"