---
- name: clone multus in local directory
  shell: git clone https://github.com/intel/multus-cni.git

- name: activate multus in the kubernetes cluster
  shell: cat /home/{{cloud_user}}/multus-cni/images/multus-daemonset.yml | kubectl apply -f -

- name: Show role bindings
  shell: kubectl get clusterrolebinding | grep compute
  register: response

- name: debug output
  debug: 
    msg: "{{ response }}"
  
- name: Show ClusterRole multus
  shell: kubectl get ClusterRole | grep multus
  register: response

- name: debug output
  debug: 
    msg: "{{ response }}"
  
- name: Network policy
  shell: kubectl label namespace/kube-system permission=talk-to-all
  register: response
  failed_when: "response.rc != 0 and 'already' not in response.stderr"

- name: debug output
  debug: 
    msg: "{{ response }}"