---
- name: setup network-attachment-definition.yaml
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
    mode: 0755
  with_items:
    - network-attachment-definition.yaml

- name: create network attachement in kubernetes
  shell: kubectl create -f /tmp/network-attachment-definition.yaml
  register: response
  changed_when: "'created' in response.stdout"
  failed_when: "response.rc != 0 and 'already exists' not in response.stderr"
- debug: msg="{{ response }}"

- name: setup multus-cluster-role.yaml
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
    mode: 0755
  with_items:
    - multus-cluster-role.yaml

- name: Multus cluster role
  shell: kubectl create -f /tmp/multus-cluster-role.yaml
  register: response
  changed_when: "'created' in response.stdout"
  failed_when: "response.rc != 0 and 'already exists' not in response.stderr"
- debug: msg="{{ response }}"

- name: Worker cluster role binding
  shell: kubectl create clusterrolebinding multus-node-{{ item }} --clusterrole=multus-crd-overpowered --user=system:node:{{ item }}
  with_items:
    - '{{ groups["node"] }}'
  register: response
  changed_when: "'created' in response.stdout"
  failed_when: "response.rc != 0 and 'already exists' not in response.stderr"
- debug: msg={{ response }}