---
- name: setup /etc/cni/net.d/10-multus_calico.conf
  template:
    src: "{{ item }}.j2"
    dest: "/etc/cni/net.d/{{ item }}"
    mode: 0644
  with_items:
    - 10-multus_calico.conf

- name: remove original calico file
  file:
    path: /etc/cni/net.d/10-calico.conflist
    state: absent

- name: Restart kubelet service
  become: true
  service:
    name: kubelet
    state: restarted
  register: service
- debug: msg="{{ service }}"