---
- name: Unmount a mounted volume
  mount:
    path: /data/
    state: unmounted

- name: update fstab to mount directory
  mount:
    path: /data/
    src: "{{ disk }}"
    fstype: "{{ fstype }}"
    opts: "rw,user,exec,umask=000"
    state: present

- name: Mount and bind a volume
  mount:
    path: /data/
    src: "{{ disk }}"
    fstype: "{{ fstype }}"
    state: mounted

- name: Create a directory /data/brick1/gv0 if it does not exist
  file:
    path: /data/brick1/gv0
    state: directory
    mode: '0755'