---
# - name: Unmount a mounted volume
#   mount:
#     path: /data/
#     state: unmounted

- name: Check if drives are already mounted
  shell: df | grep "{{ disk }}" | wc -l
  register: disk_checked

- name: debug output
  debug: 
    msg: "{{ disk_checked }}"

- name: create fstab, mount and directory
  block:
    - name: update fstab to mount directory
      mount:
        path: /glusterfs/
        src: "{{ disk }}"
        fstype: ext4
        opts: "rw"
        state: present

    - name: Mount and bind a volume
      mount:
        path: /glusterfs/
        src: "{{ disk }}"
        fstype: ext4
        state: mounted

    - name: Create a directory glusterfs distributed if it does not exist
      file:
        path: "{{ glusterfs_distributed }}"
        state: directory
        mode: '0777'
  when: 'disk_checked.stdout == "0"'
