---
- name: gluster peer probe 1
  become: true
  command: gluster peer probe {{groups['glusterfs'][1]}}
  delegate_to: "{{ groups['glusterfs'][0] }}"
  run_once: true

- name: gluster peer probe 2
  become: true
  command: gluster peer probe {{groups['glusterfs'][2]}}
  delegate_to: "{{ groups['glusterfs'][0] }}"
  run_once: true

- name: gluster peer probe 3
  become: true
  command: gluster peer probe {{groups['glusterfs'][2]}}
  delegate_to: "{{ groups['glusterfs'][1] }}"
  run_once: true

- name: gluster peer status
  become: true
  command: gluster peer status
  register: response

- name: debug response
  debug: 
    msg: "{{ response }}"

- name: gluster pool list
  become: true
  command: gluster pool list
  register: response

- name: debug response
  debug: 
    msg: "{{ response }}"

- name: create the installation directory
  file:
    path: "{{ glusterfs_distributed }}"
    state: directory

- name: create the distributed glusterfs volume named 'vol01'
  become: true
  command: gluster volume create vol01 replica 3 transport tcp {{ groups['glusterfs'][0] }}:/glusterfs/distributed {{ groups['glusterfs'][1] }}:/glusterfs/distributed {{ groups['glusterfs'][2] }}:/glusterfs/distributed force
  delegate_to: "{{ groups['glusterfs'][0] }}"
  register: response
  failed_when: "response.rc != 0 and 'already exist' not in response.stderr"


- name: gluster volume start vol01
  become: true
  command: gluster volume start vol01
  register: response
  failed_when: "response.rc != 0 and 'already started' not in response.stderr"

- name: debug response
  debug: 
    msg: "{{ response }}"

- name: gluster volume info vol01
  become: true
  command: gluster volume info vol01
  register: response

- name: debug response
  debug: 
    msg: "{{ response }}"


