---
- name: Create a directory glusterfs distributed if it does not exist
  file:
    path: "{{ glusterfs_distributed }}"
    state: directory
    mode: '0777'


- name: create gluster volume
  gluster_volume:
    state: present
    name: vol01
    bricks: "{{ glusterfs_distributed }}"
    rebalance: yes
    cluster:
      - "{{ groups['glusterfs'][0] }}"
      - "{{ groups['glusterfs'][1] }}"
      - "{{ groups['glusterfs'][2] }}"
  run_once: true
  delegate_to: "{{ groups['glusterfs'][0] }}"

- name: start gluster volume
  gluster_volume:
    state: started
    name: vol01
  register: response

