- name: check token
  become: true
  shell: sudo kubeadm token list
  register: result
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: show result
  debug:
    msg: "{{ result }}"

- name: create token
  become: true
  shell: sudo kubeadm token create
  register: token
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: show token
  debug:
    msg: "{{ token }}"

- name: create a discovery token
  become: true
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: discoveryToken
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: show discoveryToken
  debug:
    msg: "{{ discoveryToken }}"