- name: check token
  shell: sudo kubeadm token list
  register: result
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: show result
  debug:
    msg: "{{ result }}"

- name: create token
  shell: sudo kubeadm token create
  register: token
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: show token
  debug:
    msg: "{{ token }}"

- name: create a discovery token
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: discovery-token
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: show discovery-token
  debug:
    msg: "{{ discovery-token }}"