- name: Copy file with owner and permissions
  copy:
    src: "/home/{{ cloud_user }}/.ssh/{{ cloud_ssh_key_name }}"
    dest: ~/.ssh/paco_rsa
    owner: "{{ cloud_user }}"
    group: "{{ cloud_user }}"
    mode: 0600
  become_user: "{{ cloud_user }}"

- name: "generate ~/.ssh/config file"
  template:
      src: config.j2 
      dest: ~/.ssh/config 
      owner: "{{ cloud_user }}" 
      group: "{{ cloud_user }}"
      mode: '0600'
  become_user: "{{ cloud_user }}"