---
- name: Create Kubernetes addon directory
  file:
    path: "{{ network_dir }}"
    state: directory

- name: install calico cni
  block:
    - name: "Copy calico YAML files"
      template:
        src: "{{ item }}"
        dest: "{{ network_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
      with_items:
        - calico-host-local.yml.j2
      when: network == "calico"
    
    - name: "Check calico daemonset is working"
      shell: kubectl --kubeconfig={{ kubeadmin_config }} get ds --all-namespaces | grep {{ network }}
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true
      register: check_net
      ignore_errors: true
      changed_when: false
      when: network == "calico"

    - name: "Create {{ network }} network daemonset"
      when: check_net is failed and network == "calico"
      command: kubectl apply --kubeconfig={{ kubeadmin_config }} -f {{ network_dir }}/calico-host-local.yml
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true
    
    - name: Pause for 20 seconds
      pause:
        seconds: "20"
      when: network == "calico"

    - name: Check calico is running
      shell: kubectl get pods -n kube-system -o wide | grep calico-kube-controllers
      register: response
      when: network == "calico"

    - name: debug response
      debug: 
        msg: "{{ response }}"
      when: network == "calico"
  

- name: install azure cni
  block:
    - name: "Copy azure install files"
      template:
        src: "{{ item }}"
        dest: "{{ network_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
        mode: 0755
      with_fileglob:
        - ../templates/install-azure-cni-plugin.sh.j2

    - name: "install azure cni"
      shell: "{{ network_dir }}/./install-azure-cni-plugin.sh v1.0.32"
  when: network == "azure"
