---
- name: ansible distribution
  debug: 
    msg: "Ansible Distribution {{ ansible_distribution }}"

- name: ansible distribution release
  debug: 
    msg: "Ansible Distribution Release {{ ansible_distribution_release }}"

- name: ansible distribution version
  debug: 
    msg: "Ansible Distribution Version {{ ansible_distribution_version }}"  

- name: ansible distribution version
  debug: 
    msg: "Kernel Version {{ my_kernel }}"