---
- name: ansible distribution
  debug: 
    msg: 
    - "Distribution {{ ansible_distribution_release }}"
    - "Distribution Release {{ ansible_distribution_release }}"
    - "Distribution Version {{ ansible_distribution_version }}"
    - "Kernel Version {{ ansible_kernel }}"

- name: Enable SELinux
  selinux:
    policy: targeted
    state: permissive

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: '{{ hostvars[item].ansible_host }} {{item}}'
    state: present
  with_items: 
    - '{{ groups["jumphost"] }}'
    - '{{ groups["master"] }}'
    - '{{ groups["node"] }}'

- name: Restart network service
  service:
    name: network
    state: restarted