---
- name: ansible distribution
  debug: 
    msg: 
    - "Ansible Distribution {{ ansible_distribution_release }}"
    - "Ansible Distribution Release {{ ansible_distribution_release }}"
    - "Ansible Distribution Version {{ ansible_distribution_version }}" 

# - name: ansible distribution release
#   debug: 
    

# - name: ansible distribution version
#   debug: 
#     msg:  

# - name: ansible distribution version
#   debug: 
#     msg: "Kernel Version {{ my_kernel }}"