---
- name: install glusterfs
  yum: 
    name: "{{ item.pkgname }}"
    state: "present"
  with_items:
    - { pkgname: "centos-release-gluster"  }
    - { pkgname: "glusterfs-server"  }

- name: Stop the ntpd service if running on {{ inventory_hostname }}
  systemd:
    name: glusterd
    state: stopped
  register: status
- debug: msg="{{ status }}"

- name: Read device information (always use unit when probing)
  parted: device=/dev/sdc unit=MiB
  register: sdc_info
- debug: msg="{{ sdc_info }}"