---
- name: install  packages
  yum: 
    name: "{{ item.pkgname }}"
    state: "present"
  with_items:
    - { pkgname: "strongswan"  }
  
- name: Set accept redirects to 0
  become: true
  shell: echo "net.ipv4.conf.all.accept_redirects = 0" | tee -a /etc/sysctl.conf
  register: response
- debug: msg={{ response }}
  
- name: Set all send redirects to 0
  become: true
  shell: echo "net.ipv4.conf.all.send_redirects = 0" | tee -a /etc/sysctl.conf
  register: response
- debug: msg={{ response }}
  
- name: Set default rp filter to 0
  become: true
  shell: echo "net.ipv4.conf.default.rp_filter = 0" | tee -a /etc/sysctl.conf
  register: response
- debug: msg={{ response }}
  
- name: Set accept source route to 0
  become: true
  shell: echo "net.ipv4.conf.default.accept_source_route = 0" | tee -a /etc/sysctl.conf
  register: response
- debug: msg={{ response }}
  
- name: Set default send redirects to 0
  become: true
  shell: echo "net.ipv4.conf.default.send_redirects = 0" | tee -a /etc/sysctl.conf
  register: response
- debug: msg={{ response }}
  
- name: Set ICMP ingnore bogus error responses 1
  become: true
  shell: echo "net.ipv4.icmp_ignore_bogus_error_responses = 1" | tee -a /etc/sysctl.conf
  register: response
- debug: msg={{ response }}
  
- name: Set all rp filter 0
  become: true
  shell: echo "net.ipv4.conf.all.rp_filter = 0" | tee -a /etc/sysctl.conf
  register: response
- debug: msg={{ response }}
  
- name: Read systcl
  become: true
  shell: sysctl -p
  register: response
- debug: msg={{ response }}
  
- name: Show xfrm kernel modules
  become: true
  shell: lsmod | grep -i xfrm
  register: response
- debug: msg={{ response }}