---
- name: install packages on centos
  include_tasks: centos.yml
  when: linux_os == "centos"
  run_once: yes

- name: install packages on ubuntu
  include_tasks: ubuntu.yml
  when: linux_os == "ubuntu"
  run_once: yes
  
- name: install  packages
  become: true
  yum: 
    name: "{{ item.pkgname }}"
    state: "present"
  with_items:
    - { pkgname: "fuse"  }
    - { pkgname: "fuse-devel"  }
    - { pkgname: "libtool"  }
    - { pkgname: "automake"  }

- name: Git clone git://github.com/lxc/lxcfs
  become: true
  shell: git clone git://github.com/lxc/lxcfs
  register: response
  failed_when: "response.rc != 0 and 'already exists' not in response.stderr"

- name: debug output git clone
  debug: 
    msg: "{{ response}}"

- name: run bootstrap.sh
  become: true
  shell: ./bootstrap.sh
  args:
    chdir: "/home/{{ cloud_user }}/lxcfs"
  register: response

- name: run configure
  become: true
  shell: ./configure
  args:
    chdir: "/home/{{ cloud_user }}/lxcfs"
  register: response

- name: run make
  become: true
  shell: make
  args:
    chdir: "/home/{{ cloud_user }}/lxcfs"
  register: response

- name: run make install
  become: true
  shell: make install
  args:
    chdir: "/home/{{ cloud_user }}/lxcfs"
  register: response

- name: create directory /var/lib/lxcfs
  file:
    path: /var/lib/lxcfs
    state: directory
  
- name: enable lxcfs /var/lib/lxcfs
  become: true
  shell: /home/{{ cloud_user }}/lxcfs/lxcfs /var/lib/lxcfs
  register: response